import type { Product, Order } from './types';

export const ongoingOrders: Order[] = [
    { id: '1', title: 'Hand-painted wooden jewelry box', artisan: 'Priya Sharma', orderId: 'ORD-001', status: 'In Progress', image: 'https://images.pexels.com/photos/103566/pexels-photo-103566.jpeg?auto=compress&cs=tinysrgb&w=400', orderDate: '15/1/2024', estDeliveryDate: '15/2/2024', progressStep: 3 },
    { id: '2', title: 'Handwoven Silk Scarf', artisan: 'Rahul Patel', orderId: 'ORD-002', status: 'Pending Approval', image: 'https://images.pexels.com/photos/2816903/pexels-photo-2816903.jpeg?auto=compress&cs=tinysrgb&w=400', orderDate: '20/1/2024', estDeliveryDate: '20/2/2024', progressStep: 1 },
];
export const pastOrders: Order[] = [
    { id: '3', title: 'Brass Decorative Elephant', artisan: 'Meera Devi', orderId: 'ORD-003', status: 'Completed', image: 'https://images.pexels.com/photos/2361952/pexels-photo-2361952.jpeg?auto=compress&cs=tinysrgb&w=400', orderDate: '10/12/2023', estDeliveryDate: '10/1/2024', progressStep: 5 },
];
export const featuredProducts: Product[] = [
  { id: 1, name: 'Hand-painted Wooden Jewelry Box', artisan: { name: 'Priya Sharma', initial: 'P' }, price: '₹2,499', rating: 4.9, hype: 127, image: 'https://images.pexels.com/photos/103566/pexels-photo-103566.jpeg?auto=compress&cs=tinysrgb&w=400', description: 'A beautifully handcrafted wooden box, meticulously painted with a vibrant peacock motif, a symbol of grace and beauty in Indian culture. The interior is lined with soft velvet to protect your treasures.' },
  { id: 2, name: 'Brass Decorative Elephant', artisan: { name: 'Meera Devi', initial: 'M' }, price: '₹3,299', rating: 4.8, hype: 156, image: 'https://images.pexels.com/photos/2361952/pexels-photo-2361952.jpeg?auto=compress&cs=tinysrgb&w=400', description: 'This stunning brass elephant is a masterpiece of metalwork from Moradabad. Its intricate engravings and polished finish make it a perfect centerpiece for any room, symbolizing strength and wisdom.' },
  { id: 3, name: 'Silver Traditional Bangles', artisan: { name: 'Lakshmi Iyer', initial: 'L' }, price: '₹4,599', rating: 4.8, hype: 142, image: 'https://images.pexels.com/photos/1191531/pexels-photo-1191531.jpeg?auto=compress&cs=tinysrgb&w=400', description: 'A pair of elegant silver bangles, handcrafted with traditional South Indian temple jewelry designs. The detailed patterns and antique finish give them a timeless appeal for any occasion.' },
];
export const masterArtisans = [
  { id: 1, name: 'Priya Sharma', location: 'Jaipur, Rajasthan', rating: 4.9, orders: 156, initial: 'P', skills: ['Wood Carving', 'Hand Painting'] },
  { id: 2, name: 'Rahul Patel', location: 'Varanasi, UP', rating: 4.7, orders: 89, initial: 'R', skills: ['Silk Weaving', 'Traditional Textiles'] },
  { id: 3, name: 'Meera Devi', location: 'Moradabad, UP', rating: 4.8, orders: 134, initial: 'M', skills: ['Brass Work', 'Metal Crafts'] },
  { id: 4, name: 'Arjun Kumar', location: 'Khurja, UP', rating: 4.6, orders: 67, initial: 'A', skills: ['Pottery', 'Ceramic Arts'] },
  { id: 5, name: 'Fatima Khan', location: 'Kolkata, WB', rating: 4.9, orders: 73, initial: 'F', skills: ['Leather Work', 'Bookbinding'] },
  { id: 6, name: 'Lakshmi Iyer', location: 'Chennai, TN', rating: 4.8, orders: 142, initial: 'L', skills: ['Silver Jewelry', 'Traditional Metalwork'] },
];
export const discoverCreations: Product[] = [
    { id: 1, name: 'Hand-painted Wooden Jewelry Box', artisan: { name: 'Priya Sharma', location: 'Jaipur, Rajasthan', initial: 'P' }, price: '₹2,499', rating: 4.9, hype: 127, image: 'https://images.pexels.com/photos/103566/pexels-photo-103566.jpeg?auto=compress&cs=tinysrgb&w=400', tags: ['Traditional', 'Wooden'], description: 'A beautifully handcrafted wooden box, meticulously painted with a vibrant peacock motif, a symbol of grace and beauty in Indian culture. The interior is lined with soft velvet to protect your treasures.' },
    { id: 2, name: 'Brass Decorative Elephant', artisan: { name: 'Meera Devi', location: 'Moradabad, UP', initial: 'M' }, price: '₹3,299', rating: 4.8, hype: 156, image: 'https://images.pexels.com/photos/2361952/pexels-photo-2361952.jpeg?auto=compress&cs=tinysrgb&w=400', tags: ['Brass', 'Decorative'], description: 'This stunning brass elephant is a masterpiece of metalwork from Moradabad. Its intricate engravings and polished finish make it a perfect centerpiece for any room, symbolizing strength and wisdom.' },
    { id: 3, name: 'Leather Bound Journal', artisan: { name: 'Fatima Khan', location: 'Kolkata, WB', initial: 'F' }, price: '₹1,299', rating: 4.9, hype: 94, image: 'https://images.pexels.com/photos/462024/pexels-photo-462024.jpeg?auto=compress&cs=tinysrgb&w=400', tags: ['Leather', 'Handcrafted'], description: 'Capture your thoughts in this exquisite leather-bound journal. The supple leather is hand-stitched, and the recycled paper inside is perfect for writing or sketching. A timeless gift for the creative soul.' },
    { id: 4, name: 'Handwoven Silk Scarf', artisan: { name: 'Rahul Patel', location: 'Varanasi, UP', initial: 'R' }, price: '₹1,899', rating: 4.7, hype: 89, image: 'https://images.pexels.com/photos/2816903/pexels-photo-2816903.jpeg?auto=compress&cs=tinysrgb&w=400', tags: ['Silk', 'Handwoven'], description: 'Drape yourself in luxury with this handwoven silk scarf from the looms of Varanasi. The vibrant colors and delicate texture showcase the weaver\'s exceptional skill and centuries of tradition.' },
    { id: 5, name: 'Hand-painted Ceramic Vase', artisan: { name: 'Arjun Kumar', location: 'Khurja, UP', initial: 'A' }, price: '₹1,799', rating: 4.6, hype: 73, image: 'https://images.pexels.com/photos/5998050/pexels-photo-5998050.jpeg?auto=compress&cs=tinysrgb&w=400', tags: ['Ceramic', 'Hand-painted'], description: 'Add a touch of rustic charm to your home with this ceramic vase from Khurja, the pottery capital of India. Each vase is hand-painted with unique floral motifs, making it a one-of-a-kind piece of art.' },
    { id: 6, name: 'Silver Traditional Bangles', artisan: { name: 'Lakshmi Iyer', location: 'Chennai, TN', initial: 'L' }, price: '₹4,599', rating: 4.8, hype: 142, image: 'https://images.pexels.com/photos/1191531/pexels-photo-1191531.jpeg?auto=compress&cs=tinysrgb&w=400', tags: ['Silver', 'Traditional'], description: 'A pair of elegant silver bangles, handcrafted with traditional South Indian temple jewelry designs. The detailed patterns and antique finish give them a timeless appeal for any occasion.' },
    { id: 7, name: 'Madhubani Art Panel', artisan: { name: 'Sita Devi', location: 'Bihar', initial: 'S' }, price: '₹3,899', rating: 4.9, hype: 210, image: 'https://images.pexels.com/photos/16183788/pexels-photo-16183788/free-photo-of-a-painting-of-a-woman-holding-a-fish.jpeg?auto=compress&cs=tinysrgb&w=400', tags: ['Madhubani', 'Wall Art'], description: 'A captivating Madhubani painting on a wooden panel, depicting the traditional "fish" motif, a symbol of prosperity. This intricate, hand-drawn piece from the heart of Bihar will be a stunning addition to your wall decor.' },
    { id: 8, name: 'Terracotta Horse Statue', artisan: { name: 'Gopal Das', location: 'West Bengal', initial: 'G' }, price: '₹2,199', rating: 4.7, hype: 112, image: 'https://images.pexels.com/photos/159752/horse-statue-sculpture-montreal-159752.jpeg?auto=compress&cs=tinysrgb&w=400', tags: ['Terracotta', 'Decor'], description: 'This powerful terracotta horse is a classic example of Bankura craftsmanship. Its rustic finish and strong form are believed to bring positive energy and protection to the home.' },
    { id: 9, name: 'Pattachitra Scroll Painting', artisan: { name: 'Bibhu Das', location: 'Odisha', initial: 'B' }, price: '₹5,299', rating: 5.0, hype: 180, image: 'https://images.pexels.com/photos/10141629/pexels-photo-10141629.jpeg?auto=compress&cs=tinysrgb&w=400', tags: ['Pattachitra', 'Traditional'], description: 'An authentic Pattachitra scroll painting from Odisha, telling a mythological story through its vibrant, natural colors and fine-line details. This ancient art form is a true collector\'s item.' },
    { id: 10, name: 'Embroidered Cushion Covers', artisan: { name: 'Aisha Begum', location: 'Kashmir', initial: 'A' }, price: '₹1,999', rating: 4.8, hype: 99, image: 'https://images.pexels.com/photos/7195447/pexels-photo-7195447.jpeg?auto=compress&cs=tinysrgb&w=400', tags: ['Textile', 'Embroidery'], description: 'A set of two cushion covers featuring the exquisite "Aari" chain-stitch embroidery of Kashmir. The intricate floral patterns on soft cotton fabric will add a touch of elegance and warmth to your living space.' },
];
